groups:
  left_back:
    operating_mode: position
    profile_type: time
    profile_velocity: 30
    profile_acceleration: 15
    torque_enable: true

  left_middle:
    operating_mode: position
    profile_type: time
    profile_velocity: 30
    profile_acceleration: 15
    torque_enable: true

  left_front:
    operating_mode: position
    profile_type: time
    profile_velocity: 30
    profile_acceleration: 15
    torque_enable: true

  right_front:
    operating_mode: position
    profile_type: time
    profile_velocity: 30
    profile_acceleration: 15
    torque_enable: true

  right_middle:
    operating_mode: position
    profile_type: time
    profile_velocity: 30
    profile_acceleration: 15
    torque_enable: true

  right_back:
    operating_mode: position
    profile_type: time
    profile_velocity: 30
    profile_acceleration: 15
    torque_enable: true
